name: release

on: [workflow_dispatch]

jobs:
  pypi-publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    name: upload release to PyPI
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Build package
        run: |
          python -m pip install --upgrade pip 'poetry>=1.4.0'
          poetry build

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
