name: release

on: [workflow_dispatch]

jobs:
  pypi-publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    name: upload release to PyPI
    steps:
      - uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: Replace links in README.md
        run: |
          sed -i -e 's|https://github.com/\(.*\)/blob/|https://raw.githubusercontent.com/\1/|g' README.md

      - name: Build package
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          poetry build

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
